// Token Types in SomMark
const TOKEN_TYPES = {
    OPEN_BRACKET: "OPEN_BRACKET",
    CLOSE_BRACKET: "CLOSE_BRACKET",
    END_KEYWORD: "END_KEYWORD",
    IDENTIFIER: "IDENTIFIER",
    EQUAL: "EQUAL",
    VALUE: "VALUE",
    TEXT: "TEXT",
    THIN_ARROW: "THIN_ARROW",
    OPEN_PAREN: "OPEN_PAREN",
    CLOSE_PAREN: "CLOSE_PAREN",
    OPEN_AT: "OPEN_AT",
    CLOSE_AT: "CLOSE_AT",
    COLON: "COLON",
    COMMA: "COMMA",
    SEMICOLON: "SEMICOLON",
    COMMENT: "COMMENT",
    ESCAPE: "ESCAPE"
};

export default TOKEN_TYPES;
